image: python:3.5

stages:
    - test
    - quality
    - build
    - dist

cache:
    paths:
        - bin/
        - eggs/
        - parts/

before_script:
    - /bin/ping -W 1 -c 1 172.17.0.1 && export http_proxy=http://172.17.0.1:3128/
    - /bin/ping -W 1 -c 1 172.17.0.1 && export HTTP_PROXY=http://172.17.0.1:3128/
    - /bin/ping -W 1 -c 1 172.17.0.1 && export https_proxy=http://172.17.0.1:3128/
    - /bin/ping -W 1 -c 1 172.17.0.1 && export HTTPS_PROXY=http://172.17.0.1:3128/

bootstrap:
    stage: .pre
    script:
        - python3.5 bootstrap.py
        - ./bin/buildout

test-js:
    stage: test
    image: node:12.17.0
    script:
        - npm install --no-audit
        - apt update && apt install -y python3-pip
        - pip3 install anybadge
        - mkdir ./coverage
        - (npm run coverage | tee coverage/coverage.log) || true
        - GLOBAL_COVER=$(grep "All files" coverage/coverage.log | awk -F'|' '{print $2}')
        - echo "Global tests coverage is $GLOBAL_COVER %"
        - anybadge --label=Coverage --file=./coverage/coverage.svg --value="$GLOBAL_COVER" coverage
    artifacts:
        paths:
            - ./node_modules/
            - ./coverage/

eslint:
    stage: quality
    image: node:12.17.0
    allow_failure: true
    script:
        - npm install --no-audit
        - npm run eslint
    artifacts:
        paths:
            - ./node_modules/

coverage:
    stage: quality
    allow_failure: true
    image:
        name: sonarsource/sonar-scanner-cli:4.3
        entrypoint: [""]
    variables:
        SONAR_URL: http://sonar.dev-dsm.onf.fr
        SONAR_HOST_URL: http://sonar.dev-dsm.onf.fr
    script:
        - sonar-scanner -Dsonar.qualitygate.wait=true
    only:
        - merge_requests
        - master
    except:
        variables:
            - $CODE_COVERAGE_DISABLED

build-3.5:
    stage: build
    script:
        - ./bin/buildout setup setup.py clean --all sdist bdist_egg bdist_wheel
    artifacts:
        paths:
            - ./dist
    only:
        refs:
            - tags

dist-3.5:
    stage: dist
    script:
        - pip install twine
        - twine upload dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.6:
    stage: dist
    image: python:3.6
    script:
        - python3.6 bootstrap.py
        - ./bin/buildout
        - ./bin/test
        - ./bin/buildout setup setup.py bdist_egg
        - pip install twine
        - twine upload dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.7:
    stage: dist
    image: python:3.7
    script:
        - python3.7 bootstrap.py
        - ./bin/buildout
        - ./bin/test
        - ./bin/buildout setup setup.py bdist_egg
        - pip install twine
        - twine upload dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.8:
    stage: dist
    image: python:3.8
    script:
        - python3.8 bootstrap.py
        - ./bin/buildout
        - ./bin/test
        - ./bin/buildout setup setup.py bdist_egg
        - pip install twine
        - twine upload dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.9:
    stage: dist
    image: python:3.9
    script:
        - python3.9 bootstrap.py
        - ./bin/buildout
        - ./bin/test
        - ./bin/buildout setup setup.py bdist_egg
        - pip install twine
        - twine upload dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED
