matrix:
  include:
  - language: node_js
    node_js:
    - 12.17.0
    install:
    - npm install --no-audit
    - npm run coverage
    - "./node_modules/.bin/coveralls < ./coverage/lcov.info"
  - language: python
    python:
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    install:
    - python bootstrap.py
    - "./bin/buildout"
    script:
    - ./bin/test
    deploy:
      provider: pypi
      on:
        tags: true
      user: __token__
      password:
        secure: Zbtt0Qwe4ZgchcrNwNr/AcwBRtiXNWBqO9boFJMj7Z4C/jPNItJp3UJGod/hdsdsCYnjRMomIPxrNfYe97cEWPAthVEJbxUsx8B8YXFptCrfSAX8w5golz1HvezSj6fI7e9DsEn39FXiFZDr88bKyLl6ohnZ+tiADVhmLjcSdjwZcPUybyjc+EiofbuN5Ia5FcXN1+sT9JmG4JaPBbPYzdp1qbJ4mUt8WT8yKMTWD82cr3h0ya/i9/fCR0S2Qjc6qwkUUX++Jbg3oCb2Ad0Z3mpVqrvnstY0NycSbaRD5aYWSc0w+z+II9oENdA5Re7FpLhYcVuSPTf9W90YOliZCKytM22saio8HPvWgBRtq8ZfrVIDfa/SvhfA1k1Aaa99gwKmapEd0DvMfsBjbKVHn9na/NIHRDczohbEYXXPMAYM/QQ2FiD4aYnhTw9O+uD7YQ3+Fp+ES2cmuTQa8dn5JpWLUqxf0HXgYVLkLTGvZC/VebsaAaDL87FpggXcrWJV04K8xKdQXbN6F5FIKyBu9FxWeuWg5qyU5SR/KW06oEvB9VUtJ+UhkxfNaWQ8MCnugjVBDN3xqY/4J6xz9V1u0Rz9a4EjpKuL2UnhtmfDsAEZNneBFW61nTaBPCNhsUQwKXzbQYzt2GaHu9KQp2R1x3qSrpL0Ka818v/47yV+wFo=
      distributions: sdist bdist_egg bdist_wheel
      skip_existing: true
