@startuml

(*) --> "MyAMS.form.submit()"

--> "getFormSettings()"

If "formData.submitted?" then
    -left-> [yes] submitWarning()
    --> (*)
else
    --> checkValidators()
    If "status == 'success' ?" then
        --> [yes] "<u>clearAlerts</u>()"
        --> "<u>initSubmitButton</u>()"
        --> "<u>getData()"
        --> "<u>initData(veto)"
        If "veto.veto?" then
            -left-> [yes] "<u>resetSubmitButton</u>()" as rsb1
            --> (*)
        else
            --> "<u>getTarget</u>()"
            If "target?" then
                -right-> [yes] "<u>initTarget</u>()"
                --> "<u>getAction</u>()"
            else
                --> "<u>getAction</u>()"
            Endif
            --> "<u>getAjaxSettings</u>()"
            --> "<u>getDownloadTarget</u>()"
            If "download target ?" then
                -right-> [yes] "<u>initDownloadTarget</u>()"
                --> "<u>getProgressSettings</u>()"
            else
                --> "<u>getProgressSettings</u>()"
            Endif
            --> "<u>submit</u>()"
            If "has progress handler?" then
                -right-> [yes] "<u>getProgressState</u>()"
                --> "ajaxSubmit()"
            else
                --> [no] "ajaxSubmit()"
            Endif
            If "download target?" then
                -right-> [yes] "<u>resetDownloadTarget</u>()"
                --> "<i>AJAX status handler</i>"
            else
                --> [no] "<i>AJAX status handler</i>"
            End If
            If "" then
                -right-> [success] "<b>event</b>\nsubmit-success.ams.form"
                If "veto.veto?" then
                    -right-> [true] (*)
                else
                    If "modal form?" then
                        -right-> [yes] "modal.close()"
                        --> "<u>submitCallback</u>()" as sc
                    else
                        --> [no] sc
                    Endif
                    --> "<u>resetAfterSubmit</u>()" as ras2
                    --> "<u>resetChanged</u>()" as rc2
                    --> (*)
                Endif
            else
                -left-> [error] "<b>event</b>\nsubmit-error.ams.form"
                If "target?" then
                    -right-> [yes] "<u>resetAfterError</u>()" as rae3
                    --> "<u>resetAfterSubmit</u>()" as ras3
                else
                    --> [no] ras3
                Endif
                --> (*)
            Endif
        Endif
    else
        --> [no] (*)
    Endif
Endif

@enduml
